name: Flutter Build

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:  # 允许手动触发

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.2'  # 更新为你的Flutter版本
          channel: 'stable'
      
      - name: Get dependencies
        run: flutter pub get
      
      - name: Build APK for different architectures
        run: |
          flutter build apk --release --split-per-abi
          mv build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk build/app/outputs/flutter-apk/app-arm32-release.apk
          mv build/app/outputs/flutter-apk/app-arm64-v8a-release.apk build/app/outputs/flutter-apk/app-arm64-release.apk
          mv build/app/outputs/flutter-apk/app-x86_64-release.apk build/app/outputs/flutter-apk/app-x86_64-release.apk
      
      - name: Upload APKs
        uses: actions/upload-artifact@v3
        with:
          name: app-release-apks
          path: |
            build/app/outputs/flutter-apk/app-arm32-release.apk
            build/app/outputs/flutter-apk/app-arm64-release.apk
            build/app/outputs/flutter-apk/app-x86_64-release.apk
